name: random

#TODO: make these the source of truth and pass them into docker build somehow
config:
  http_port: 8000
  healthcheck_port: 9000

containers:
- dockerfile: docker/Dockerfile
  context: .

profiles:
  stable:
    endpoint: /random/
    max_memory: 0.5G
    max_cpu: 0.5
  canary:
    endpoint: /random/
    weight: 10
    max_memory: 0.25G
    max_cpu: 0.25
  default:
    name: {{branch.replace('/', '-')}}
    endpoint: /preview/random/{{branch}}/
    max_memory: 0.25G
    max_cpu: 0.25
