apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: jmcclell/svc-go-random
profiles:
- name: dev
  deploy:
    kustomize:
      path: './k8s/overlays/development/'
- name: test
  test:
    - image: jmcclell/svc-go-random
      structureTests:
      - './k8s/structure-tests/*'
- name: prod
  deploy:
    kustomize:
      path: './k8s/overlays/production/'
